/*
 * ConformanceTest.kt
 *
 * Pins the Kotlin port to src/orb.js through the vectors generated by
 * native/conformance/generate.mjs. See native/SPEC.md §7.
 */
package com.earlbalai.orb

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertThrows
import org.junit.Test
import kotlin.math.sin

class ConformanceTest {

  @Test fun huesMatchReference() {
    assertEquals(ConformanceVectors.hues, OrbIdentity.HUES)
  }

  @Test fun builtInPalettes() {
    ConformanceVectors.palettes.forEachIndexed { i, v ->
      val p = OrbIdentity.PALETTES[i]
      assertEquals(v.hue, p.hue!!, 0.0)
      assertEquals("anchor for hue ${v.hue}", v.anchor, p.anchor.hex)
      assertEquals("accents for hue ${v.hue}", v.accents, p.accents.map { it.hex })
    }
  }

  @Test fun customHues() {
    for (v in ConformanceVectors.customHues) {
      val p = OrbPalette.ofHue(v.input)
      assertEquals("hue wrap for ${v.input}", v.hue, p.hue!!, 1e-9)
      assertEquals("anchor for hue ${v.input}", v.anchor, p.anchor.hex)
      assertEquals("accents for hue ${v.input}", v.accents, p.accents.map { it.hex })
    }
  }

  @Test fun identityForEverySeed() {
    for (v in ConformanceVectors.identity) {
      val id = OrbIdentity(v.seed)
      assertEquals("hash of '${v.seed}'", v.hash, id.hash)
      assertEquals("archetype of '${v.seed}'", v.archetypeIndex, id.archetype.index)
      assertEquals("hue of '${v.seed}'", v.hue, id.palette.hue!!, 0.0)
      assertEquals(v.anchor, id.palette.anchor.hex)
      assertEquals(v.accents, id.palette.accents.map { it.hex })
      assertEquals(v.phase, id.phase, 1e-9)
      assertEquals(v.spin, id.spin, 1e-9)
      assertEquals(v.timeOffset, id.timeOffset, 1e-9)
    }
  }

  private fun syntheticLevel(t: Double): Double {
    val phrase = 0.55 + 0.45 * sin(0.9 * t + 2 * sin(0.37 * t))
    val syllable = 0.6 + 0.4 * sin(6.2 * t + 3 * sin(2.3 * t))
    val breath = if (sin(0.7 * t + 1.7) > -0.6) 1.0 else 0.12
    return phrase * syllable * breath
  }

  private fun stateAt(t: Double): Double = when {
    t < 1 -> 0.0
    t < 3 -> 1.0
    t < 5 -> 2.0
    t < 9 -> 3.0
    else -> 0.0
  }

  /** Same scenario as generate.mjs. */
  @Test fun dynamicsScenario() {
    for (sc in ConformanceVectors.dynamics) {
      val id = OrbIdentity(sc.seed)
      val d = OrbDynamics()
      d.reseed(id)
      d.setState(0.0, instant = true)
      var time = id.timeOffset
      val it = sc.samples.iterator()
      var next: DynamicsSample? = if (it.hasNext()) it.next() else null

      for (i in 0..sc.steps) {
        val t = i * sc.dt
        d.state = stateAt(t)
        d.level = syntheticLevel(t)
        if (i > 0) time += sc.dt
        d.advance(time)

        val s = next
        if (s != null && s.step == i) {
          val where = "seed '${sc.seed}' step $i"
          assertEquals("stateBlend $where", s.stateBlend, d.stateBlend, 1e-4)
          assertEquals("drive $where", s.drive, d.drive, 1e-4)
          assertEquals("audioSlow $where", s.audioSlow, d.audioSlow, 1e-4)
          assertEquals("audioFast $where", s.audioFast, d.audioFast, 1e-4)
          assertEquals("spin $where", s.spin, d.spin, 2e-3)
          assertEquals("spinVel $where", s.spinVel, d.spinVel, 2e-3)
          assertEquals("spinDir $where", s.spinDir, d.spinDir, 0.0)
          next = if (it.hasNext()) it.next() else null
        }
      }
      assertNull("every sample consumed", next)
    }
  }

  @Test fun resolutionRules() {
    assertEquals(640, OrbResolution.pixels(320.0, 3.0))
    assertEquals(640, OrbResolution.pixels(320.0, 2.0))
    assertEquals(320, OrbResolution.pixels(320.0, 1.0))
    assertEquals(40, OrbResolution.pixels(40.0, 3.0))
    assertEquals(1280, OrbResolution.pixels(2000.0, 2.0))
    assertEquals(8, OrbResolution.pixels(8.0, 1.0))
    assertEquals(0.4 * OrbMath.clamp(420.0 / 640.0, 0.55, 1.0), OrbResolution.lens(OrbLensChoice.Auto, 320.0, 640), 1e-12)
    assertEquals(0.0, OrbResolution.lens(OrbLensChoice.Auto, 40.0, 40), 0.0)
    assertEquals(0.0, OrbResolution.lens(OrbLensChoice.Off, 320.0, 640), 0.0)
    assertEquals(0.9, OrbResolution.lens(OrbLensChoice.Amplitude(0.9), 320.0, 640), 0.0)
  }

  @Test fun optionValidation() {
    assertThrows(IllegalArgumentException::class.java) { OrbOptions(size = 4.0).validate() }
    assertThrows(IllegalArgumentException::class.java) { OrbOptions(state = 3.5).validate() }
    assertThrows(IllegalArgumentException::class.java) { OrbOptions(lens = OrbLensChoice.Amplitude(-1.0)).validate() }
    OrbOptions(state = 2.5).validate()
  }

  @Test fun colorHexRoundTrip() {
    assertEquals("#e98c13", OrbColor.fromHex("#e98c13")!!.hex)
    assertEquals("#ffffff", OrbColor.fromHex("fff")!!.hex)
    assertNull(OrbColor.fromHex("not a colour"))
  }

  @Test fun shaderTextIsWellFormed() {
    // The fragment program is assembled from three pieces; make sure they line up.
    val fs = OrbShaders.FRAGMENT
    for (u in OrbShaders.UNIFORMS) assert(fs.contains("uniform") && fs.contains(u)) { "missing uniform $u" }
    assert(fs.contains("vec4 shade(vec2 p)")) { "galaxy body missing" }
    assert(fs.contains("void main()")) { "main missing" }
    assert(fs.count { it == '{' } == fs.count { it == '}' }) { "unbalanced braces" }
  }
}
