// Generated by native/conformance/generate.mjs from src/orb.js@1.0.0. Do not edit.
// swiftlint:disable all
import Foundation

struct IdentityVector {
  let seed: String; let hash: UInt32; let hue: Double; let archetypeIndex: Int
  let phase: Double; let spin: Double; let timeOffset: Double
  let anchor: String; let accents: [String]
}
struct DynamicsSample {
  let step: Int; let time: Double; let stateBlend: Double; let drive: Double
  let audioSlow: Double; let audioFast: Double; let spin: Double; let spinVel: Double; let spinDir: Double
}
struct DynamicsVector { let seed: String; let dt: Double; let steps: Int; let sampleEvery: Int; let samples: [DynamicsSample] }
struct PaletteVector { let hue: Double; let anchor: String; let accents: [String] }
struct CustomHueVector { let input: Double; let hue: Double; let anchor: String; let accents: [String] }

enum ConformanceVectors {
  static let hues: [Double] = [13, 34, 125, 146, 166, 187, 208, 228, 249, 270, 290, 311, 332, 353]
  static let palettes: [PaletteVector] = [
    PaletteVector(hue: 13, anchor: "#ed4f24", accents: ["#fb8f71", "#f6cfaa", "#fcf3cf"]),
    PaletteVector(hue: 34, anchor: "#e98c13", accents: ["#fbb65d", "#f3e497", "#f4fcc2"]),
    PaletteVector(hue: 125, anchor: "#13ec25", accents: ["#60fb6d", "#9af4ba", "#c5fce9"]),
    PaletteVector(hue: 146, anchor: "#13e86f", accents: ["#5cfba1", "#97f3d8", "#c1fcfc"]),
    PaletteVector(hue: 166, anchor: "#13e5b4", accents: ["#58fbd5", "#93f0f3", "#bee7fc"]),
    PaletteVector(hue: 187, anchor: "#13d0e9", accents: ["#5de8fb", "#97d0f3", "#c2d4fc"]),
    PaletteVector(hue: 208, anchor: "#238fed", accents: ["#71bbfb", "#aabef6", "#d0cffc"]),
    PaletteVector(hue: 228, anchor: "#365bef", accents: ["#748ffb", "#b1acf6", "#dfcffc"]),
    PaletteVector(hue: 249, anchor: "#583def", accents: ["#8874fb", "#cbacf6", "#efcffc"]),
    PaletteVector(hue: 270, anchor: "#9133ee", accents: ["#b874fb", "#e5acf6", "#fccff9"]),
    PaletteVector(hue: 290, anchor: "#cd29ee", accents: ["#e574fb", "#f6acee", "#fccfea"]),
    PaletteVector(hue: 311, anchor: "#ed27c9", accents: ["#fb74e3", "#f6acd5", "#fccfda"]),
    PaletteVector(hue: 332, anchor: "#ee2b86", accents: ["#fb74b3", "#f6acbb", "#fcd3cf"]),
    PaletteVector(hue: 353, anchor: "#ee2e45", accents: ["#fb7484", "#f6b7ac", "#fce3cf"]),
  ]
  static let customHues: [CustomHueVector] = [
    CustomHueVector(input: 0, hue: 0, anchor: "#ee3030", accents: ["#fb7474", "#f6c0ac", "#fce9cf"]),
    CustomHueVector(input: 7.5, hue: 7.5, anchor: "#ee4129", accents: ["#fb8574", "#f6c9ac", "#fceecf"]),
    CustomHueVector(input: 90, hue: 90, anchor: "#79df12", accents: ["#a6fb52", "#a5f28d", "#b8fbbc"]),
    CustomHueVector(input: 180, hue: 180, anchor: "#12e2e2", accents: ["#56fbfb", "#91d9f3", "#bbd7fb"]),
    CustomHueVector(input: 200.25, hue: 200.25, anchor: "#1ca6ed", accents: ["#6acafb", "#a3c3f5", "#ced3fc"]),
    CustomHueVector(input: 359.9, hue: 359.9, anchor: "#ee3030", accents: ["#fb7474", "#f6c0ac", "#fce8cf"]),
    CustomHueVector(input: 360, hue: 0, anchor: "#ee3030", accents: ["#fb7474", "#f6c0ac", "#fce9cf"]),
    CustomHueVector(input: 720, hue: 0, anchor: "#ee3030", accents: ["#fb7474", "#f6c0ac", "#fce9cf"]),
    CustomHueVector(input: -30, hue: 330, anchor: "#ee2a8c", accents: ["#fb74b8", "#f6acbe", "#fcd2cf"]),
    CustomHueVector(input: 1000000, hue: 280, anchor: "#ae2eee", accents: ["#ce74fb", "#f1acf6", "#fccff2"]),
  ]
  static let identity: [IdentityVector] = [
    IdentityVector(seed: "", hash: 2166136261, hue: 270, archetypeIndex: 0, phase: 2.898, spin: 10.722600000000002, timeOffset: 195.7, anchor: "#9133ee", accents: ["#b874fb", "#e5acf6", "#fccff9"]),
    IdentityVector(seed: "a", hash: 3826002220, hue: 332, archetypeIndex: 0, phase: 0.785, spin: 2.9045, timeOffset: 219.64, anchor: "#ee2b86", accents: ["#fb74b3", "#f6acbb", "#fcd3cf"]),
    IdentityVector(seed: "agent-42", hash: 166409783, hue: 34, archetypeIndex: 3, phase: 4.528, spin: 16.7536, timeOffset: 98.94, anchor: "#e98c13", accents: ["#fbb65d", "#f3e497", "#f4fcc2"]),
    IdentityVector(seed: "agent-43", hash: 149632164, hue: 290, archetypeIndex: 3, phase: 2.519, spin: 9.320300000000001, timeOffset: 243.74, anchor: "#cd29ee", accents: ["#e574fb", "#f6acee", "#fccfea"]),
    IdentityVector(seed: "Agent-42", hash: 592842327, hue: 228, archetypeIndex: 2, phase: 3.579, spin: 13.242300000000002, timeOffset: 352.77, anchor: "#365bef", accents: ["#748ffb", "#b1acf6", "#dfcffc"]),
    IdentityVector(seed: "orb", hash: 2669540626, hue: 166, archetypeIndex: 1, phase: 0.737, spin: 2.7269, timeOffset: 255.53, anchor: "#13e5b4", accents: ["#58fbd5", "#93f0f3", "#bee7fc"]),
    IdentityVector(seed: "Orb.js", hash: 4276135947, hue: 353, archetypeIndex: 0, phase: 1.543, spin: 5.7091, timeOffset: 199.03, anchor: "#ee2e45", accents: ["#fb7484", "#f6b7ac", "#fce3cf"]),
    IdentityVector(seed: "hello world", hash: 3582672807, hue: 228, archetypeIndex: 3, phase: 5.679, spin: 21.012300000000003, timeOffset: 316.74, anchor: "#365bef", accents: ["#748ffb", "#b1acf6", "#dfcffc"]),
    IdentityVector(seed: "0", hash: 890022063, hue: 228, archetypeIndex: 0, phase: 3.698, spin: 13.6826, timeOffset: 358.74, anchor: "#365bef", accents: ["#748ffb", "#b1acf6", "#dfcffc"]),
    IdentityVector(seed: "1", hash: 873244444, hue: 125, archetypeIndex: 0, phase: 1.689, spin: 6.249300000000001, timeOffset: 103.46, anchor: "#13ec25", accents: ["#60fb6d", "#9af4ba", "#c5fce9"]),
    IdentityVector(seed: "42", hash: 2279835011, hue: 353, archetypeIndex: 3, phase: 4.48, spin: 16.576000000000004, timeOffset: 236.07, anchor: "#ee2e45", accents: ["#fb7484", "#f6b7ac", "#fce3cf"]),
    IdentityVector(seed: "12345678901234567890", hash: 686313437, hue: 187, archetypeIndex: 0, phase: 2.498, spin: 9.242600000000001, timeOffset: 3.08, anchor: "#13d0e9", accents: ["#5de8fb", "#97d0f3", "#c2d4fc"]),
    IdentityVector(seed: "user_7f3a9c", hash: 3709468186, hue: 166, archetypeIndex: 1, phase: 3.835, spin: 14.1895, timeOffset: 68.52, anchor: "#13e5b4", accents: ["#58fbd5", "#93f0f3", "#bee7fc"]),
    IdentityVector(seed: "c0ffee", hash: 4025827056, hue: 208, archetypeIndex: 1, phase: 1.089, spin: 4.0293, timeOffset: 23.49, anchor: "#238fed", accents: ["#71bbfb", "#aabef6", "#d0cffc"]),
    IdentityVector(seed: "the quick brown fox", hash: 865043906, hue: 208, archetypeIndex: 3, phase: 0.466, spin: 1.7242000000000002, timeOffset: 183.21, anchor: "#238fed", accents: ["#71bbfb", "#aabef6", "#d0cffc"]),
    IdentityVector(seed: "sk-live-abcdef", hash: 2296639768, hue: 290, archetypeIndex: 3, phase: 2.212, spin: 8.184400000000002, timeOffset: 92.33, anchor: "#cd29ee", accents: ["#e574fb", "#f6acee", "#fccfea"]),
    IdentityVector(seed: "ゆき", hash: 2804294108, hue: 13, archetypeIndex: 2, phase: 2.718, spin: 10.0566, timeOffset: 318.16, anchor: "#ed4f24", accents: ["#fb8f71", "#f6cfaa", "#fcf3cf"]),
    IdentityVector(seed: "émilie", hash: 2887510288, hue: 332, archetypeIndex: 3, phase: 0.563, spin: 2.0831, timeOffset: 368.08, anchor: "#ee2b86", accents: ["#fb74b3", "#f6acbb", "#fcd3cf"]),
    IdentityVector(seed: "🪐", hash: 3441898147, hue: 270, archetypeIndex: 3, phase: 1.634, spin: 6.0458, timeOffset: 18.9, anchor: "#9133ee", accents: ["#b874fb", "#e5acf6", "#fccff9"]),
    IdentityVector(seed: "seed with spaces  ", hash: 4131426643, hue: 34, archetypeIndex: 0, phase: 2.295, spin: 8.4915, timeOffset: 147.58, anchor: "#e98c13", accents: ["#fbb65d", "#f3e497", "#f4fcc2"]),
    IdentityVector(seed: "UPPER", hash: 2906723303, hue: 34, archetypeIndex: 1, phase: 0.164, spin: 0.6068, timeOffset: 318.4, anchor: "#e98c13", accents: ["#fbb65d", "#f3e497", "#f4fcc2"]),
    IdentityVector(seed: "lower", hash: 3038577850, hue: 13, archetypeIndex: 1, phase: 5.956, spin: 22.037200000000002, timeOffset: 267.8, anchor: "#ed4f24", accents: ["#fb8f71", "#f6cfaa", "#fcf3cf"]),
    IdentityVector(seed: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", hash: 3647934341, hue: 270, archetypeIndex: 3, phase: 5.692, spin: 21.0604, timeOffset: 65.39, anchor: "#9133ee", accents: ["#b874fb", "#e5acf6", "#fccff9"]),
    IdentityVector(seed: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", hash: 3018110693, hue: 146, archetypeIndex: 0, phase: 2.53, spin: 9.360999999999999, timeOffset: 268.48, anchor: "#13e86f", accents: ["#5cfba1", "#97f3d8", "#c1fcfc"]),
  ]
  static let dynamics: [DynamicsVector] = [
    DynamicsVector(seed: "agent-42", dt: 0.016666666666666666, steps: 600, sampleEvery: 30, samples: [
      DynamicsSample(step: 0, time: 98.94, stateBlend: 0, drive: 0.0726, audioSlow: 0, audioFast: 0, spin: 16.7536, spinVel: 0, spinDir: -1),
      DynamicsSample(step: 30, time: 99.43999999999997, stateBlend: 0, drive: 0.0826791761001287, audioSlow: 0.07863428929410467, audioFast: 0.07592297076725243, spin: 16.74022758855769, spinVel: 0.06355513846971317, spinDir: -1),
      DynamicsSample(step: 60, time: 99.93999999999994, stateBlend: 0.12967527416660263, drive: 0.27362247272563944, audioSlow: 0.2166456164479006, audioFast: 0.233754876746453, spin: 16.710925307750934, spinVel: -0.13687208199025902, spinDir: -1),
      DynamicsSample(step: 90, time: 100.43999999999991, stateBlend: 0.9865066128670779, drive: 0.8041408066184874, audioSlow: 0.809242135990726, audioFast: 0.8286382391091544, spin: 16.248124923335755, spinVel: -1.2053823771611314, spinDir: -1),
      DynamicsSample(step: 120, time: 100.93999999999988, stateBlend: 1, drive: 0.3293944115396371, audioSlow: 0.5952864642918129, audioFast: 0.5268851185752996, spin: 15.663524680725637, spinVel: -1.024817796794892, spinDir: -1),
      DynamicsSample(step: 150, time: 101.43999999999986, stateBlend: 1, drive: 0.2568103013408823, audioSlow: 0.2611977488803016, audioFast: 0.2497045835115144, spin: 15.345666871831472, spinVel: -0.36513052178345645, spinDir: -1),
      DynamicsSample(step: 180, time: 101.93999999999983, stateBlend: 1.1296752741666025, drive: 0.045553863537139645, audioSlow: 0.1160093719310246, audioFast: 0.0917107731745116, spin: 15.274447850307721, spinVel: 0.05470488078656511, spinDir: -1),
      DynamicsSample(step: 210, time: 102.4399999999998, stateBlend: 1.9865066128670779, drive: 0.3702947562469495, audioSlow: 0.35825065773007253, audioFast: 0.36989259833894134, spin: 15.593258022223385, spinVel: 1.1395197504000423, spinDir: -1),
      DynamicsSample(step: 240, time: 102.93999999999977, stateBlend: 2, drive: 0.29843264954950227, audioSlow: 0.34001741859810247, audioFast: 0.3310445973217297, spin: 16.25864513507234, spinVel: 1.426579479804228, spinDir: -1),
      DynamicsSample(step: 270, time: 103.43999999999974, stateBlend: 2, drive: 0.21511077663007228, audioSlow: 0.24823993823957965, audioFast: 0.2283686517706562, spin: 16.96685946642757, spinVel: 1.3793140834712043, spinDir: -1),
      DynamicsSample(step: 300, time: 103.93999999999971, stateBlend: 2.1296752741666025, drive: 0.4307623790557643, audioSlow: 0.39983461978419804, audioFast: 0.43699484255056464, spin: 17.694876344916576, spinVel: 1.598742364946346, spinDir: -1),
      DynamicsSample(step: 330, time: 104.43999999999969, stateBlend: 2.9865066128670783, drive: 0.06186074569290193, audioSlow: 0.1624667080436291, audioFast: 0.11621264308534343, spin: 18.22716400714605, spinVel: 0.8486100425716017, spinDir: 1),
      DynamicsSample(step: 360, time: 104.93999999999966, stateBlend: 3, drive: 0.7502134776651543, audioSlow: 0.7149977487777177, audioFast: 0.7990605893908235, spin: 18.903112241423212, spinVel: 2.0757741346072445, spinDir: 1),
      DynamicsSample(step: 390, time: 105.43999999999963, stateBlend: 3, drive: 0.18151236765070075, audioSlow: 0.35354917090182963, audioFast: 0.27305755838864315, spin: 19.885027528734664, spinVel: 1.6632019496849668, spinDir: 1),
      DynamicsSample(step: 420, time: 105.9399999999996, stateBlend: 3, drive: 0.19341146583118835, audioSlow: 0.21939359212573395, audioFast: 0.19435710526640407, spin: 20.56274095379842, spinVel: 1.149728179991947, spinDir: 1),
      DynamicsSample(step: 450, time: 106.43999999999957, stateBlend: 3, drive: 0.40109778713369515, audioSlow: 0.29213908032207375, audioFast: 0.34933757749502203, spin: 21.109414607940558, spinVel: 1.2490800243412956, spinDir: 1),
      DynamicsSample(step: 480, time: 106.93999999999954, stateBlend: 3, drive: 0.22689415737627333, audioSlow: 0.6905020152267514, audioFast: 0.6419193771329958, spin: 22.138536015677385, spinVel: 2.3134892313743416, spinDir: 1),
      DynamicsSample(step: 510, time: 107.43999999999951, stateBlend: 3, drive: 0.22123577929940433, audioSlow: 0.6779177149310038, audioFast: 0.633174631221699, spin: 23.359646750007673, spinVel: 2.502715793175212, spinDir: 1),
      DynamicsSample(step: 540, time: 107.93999999999949, stateBlend: 2.610974177500192, drive: 0.712522340181799, audioSlow: 0.9158195837766957, audioFast: 0.9538406443608909, spin: 24.609631728302, spinVel: 2.717884771501688, spinDir: 1),
      DynamicsSample(step: 570, time: 108.43999999999946, stateBlend: 0.0404801613987663, drive: 0.1700332578421981, audioSlow: 0.4251113123357797, audioFast: 0.3110689098014204, spin: 25.751208591910363, spinVel: 1.758724582882233, spinDir: 1),
      DynamicsSample(step: 600, time: 108.93999999999943, stateBlend: 0, drive: 0.15171483911926567, audioSlow: 0.21598074651535765, audioFast: 0.1747639591069982, spin: 26.384686576282732, spinVel: 0.8450609988871356, spinDir: -1),
    ]),
    DynamicsVector(seed: "orb", dt: 0.016666666666666666, steps: 600, sampleEvery: 30, samples: [
      DynamicsSample(step: 0, time: 255.53, stateBlend: 0, drive: 0.0726, audioSlow: 0, audioFast: 0, spin: 2.7269, spinVel: 0, spinDir: -1),
      DynamicsSample(step: 30, time: 256.03000000000037, stateBlend: 0, drive: 0.0826791761001287, audioSlow: 0.07863428929409995, audioFast: 0.07592297076723567, spin: 2.7085890604173755, spinVel: 0.04812514218080627, spinDir: -1),
      DynamicsSample(step: 60, time: 256.5299999999999, stateBlend: 0.1296752741664995, drive: 0.2736224727255485, audioSlow: 0.21664561644787006, audioFast: 0.23375487674640807, spin: 2.6706292555093607, spinVel: -0.1550794596045444, spinDir: -1),
      DynamicsSample(step: 90, time: 257.02999999999946, stateBlend: 0.9865066128670283, drive: 0.8041408066184816, audioSlow: 0.8092421359906372, audioFast: 0.828638239109123, spin: 2.1970424524633563, spinVel: -1.2295696356620716, spinDir: -1),
      DynamicsSample(step: 120, time: 257.529999999999, stateBlend: 1, drive: 0.3293944115396371, audioSlow: 0.5952864642919099, audioFast: 0.5268851185754156, spin: 1.6001188514947358, spinVel: -1.0492382664380666, spinDir: -1),
      DynamicsSample(step: 150, time: 258.02999999999855, stateBlend: 1, drive: 0.2568103013408823, audioSlow: 0.26119774888042024, audioFast: 0.2497045835115049, spin: 1.2705504808235877, spinVel: -0.3874300992389035, spinDir: -1),
      DynamicsSample(step: 180, time: 258.5299999999981, stateBlend: 1.1296752741664995, drive: 0.04749157756508827, audioSlow: 0.11611408702628052, audioFast: 0.09188213529649397, spin: 1.1888982037253932, spinVel: 0.035141700322673525, spinDir: -1),
      DynamicsSample(step: 210, time: 259.02999999999764, stateBlend: 1.9865066128670283, drive: 0.6093331254374099, audioSlow: 0.5856641839218791, audioFast: 0.6128752176898434, spin: 1.5602069249289283, spinVel: 1.3816527056085248, spinDir: -1),
      DynamicsSample(step: 240, time: 259.5299999999972, stateBlend: 2, drive: 0.30120572110809485, audioSlow: 0.4544948982192678, audioFast: 0.411346276440059, spin: 2.3442245197985896, spinVel: 1.6196212143212498, spinDir: -1),
      DynamicsSample(step: 270, time: 260.02999999999673, stateBlend: 2, drive: 0.20981988403875204, audioSlow: 0.25294537870627704, audioFast: 0.21554549001907483, spin: 3.1034770442769286, spinVel: 1.4107921751638384, spinDir: -1),
      DynamicsSample(step: 300, time: 260.5299999999963, stateBlend: 2.1296752741664995, drive: 0.3263918102427373, audioSlow: 0.327540160888578, audioFast: 0.34391792108676106, spin: 3.820540441471394, spinVel: 1.4729782696936082, spinDir: -1),
      DynamicsSample(step: 330, time: 261.0299999999958, stateBlend: 2.986506612867028, drive: 0.06161229922292089, audioSlow: 0.13594190500442388, audioFast: 0.1007477970511882, spin: 4.35708648985535, spinVel: 0.9061759510188707, spinDir: 1),
      DynamicsSample(step: 360, time: 261.52999999999537, stateBlend: 3, drive: 0.7502134776651543, audioSlow: 0.7144455053948542, audioFast: 0.7990591012991144, spin: 5.048551073166866, spinVel: 2.0931832338278, spinDir: 1),
      DynamicsSample(step: 390, time: 262.0299999999949, stateBlend: 3, drive: 0.18151236765070075, audioSlow: 0.3534544094599024, audioFast: 0.27305746586440743, spin: 6.036482218801568, spinVel: 1.6729237173265747, spinDir: 1),
      DynamicsSample(step: 420, time: 262.52999999999446, stateBlend: 3, drive: 0.19341146583118835, audioSlow: 0.21937569400130746, audioFast: 0.19435709951357924, spin: 6.719287865893418, spinVel: 1.1609757801533027, spinDir: 1),
      DynamicsSample(step: 450, time: 263.029999999994, stateBlend: 3, drive: 0.40109778713369515, audioSlow: 0.29213801154598384, audioFast: 0.3493375774922099, spin: 7.272479075872495, spinVel: 1.2639118316754707, spinDir: 1),
      DynamicsSample(step: 480, time: 263.52999999999355, stateBlend: 3, drive: 0.22689415737627333, audioSlow: 0.6905019856079538, audioFast: 0.6419193771331657, spin: 8.310023777573285, spinVel: 2.3322193305625443, spinDir: 1),
      DynamicsSample(step: 510, time: 264.0299999999931, stateBlend: 3, drive: 0.22123577929940433, audioSlow: 0.6779177131623979, audioFast: 0.6331746312218636, spin: 9.541482040613198, spinVel: 2.525213597991236, spinDir: 1),
      DynamicsSample(step: 540, time: 264.52999999999264, stateBlend: 2.6109741775005015, drive: 0.7469102532960212, audioSlow: 0.9176779248105603, audioFast: 0.9568817462347257, spin: 10.803644555988361, spinVel: 2.7445125481495607, spinDir: 1),
      DynamicsSample(step: 570, time: 265.0299999999922, stateBlend: 0.040480161398915, drive: 0.17003325784224352, audioSlow: 0.4298285676037464, audioFast: 0.3133771314481964, spin: 11.962251850794114, spinVel: 1.7893157605651007, spinDir: 1),
      DynamicsSample(step: 600, time: 265.52999999999173, stateBlend: 0, drive: 0.15171483911926567, audioSlow: 0.21687172094790785, audioFast: 0.17490747630569378, spin: 12.607900007510608, spinVel: 0.8652019619571899, spinDir: -1),
    ]),
    DynamicsVector(seed: "", dt: 0.016666666666666666, steps: 600, sampleEvery: 30, samples: [
      DynamicsSample(step: 0, time: 195.7, stateBlend: 0, drive: 0.0726, audioSlow: 0, audioFast: 0, spin: 10.722600000000002, spinVel: 0, spinDir: 1),
      DynamicsSample(step: 30, time: 196.2000000000004, stateBlend: 0, drive: 0.0826791761001287, audioSlow: 0.07863428929410099, audioFast: 0.07592297076724047, spin: 10.883063937787442, spinVel: 0.39904292669808833, spinDir: 1),
      DynamicsSample(step: 60, time: 196.70000000000078, stateBlend: 0.12967527416670566, drive: 0.27362247272573026, audioSlow: 0.21664561644793098, audioFast: 0.2337548767464979, spin: 11.175638119577581, spinVel: 0.698993712552281, spinDir: 1),
      DynamicsSample(step: 90, time: 197.20000000000118, stateBlend: 0.9865066128671275, drive: 0.8041408066184933, audioSlow: 0.809242135990815, audioFast: 0.8286382391091855, spin: 11.980542577640714, spinVel: 1.99114806508402, spinDir: 1),
      DynamicsSample(step: 120, time: 197.70000000000158, stateBlend: 1, drive: 0.3293944115396371, audioSlow: 0.5952864642917163, audioFast: 0.526885118575184, spin: 12.97837176987634, spinVel: 1.8706588678492932, spinDir: 1),
      DynamicsSample(step: 150, time: 198.20000000000198, stateBlend: 1, drive: 0.2568103013408823, audioSlow: 0.26119774888018343, audioFast: 0.24970458351152391, spin: 13.719409060665475, spinVel: 1.2076169462568527, spinDir: 1),
      DynamicsSample(step: 180, time: 198.70000000000238, stateBlend: 1.1296752741667055, drive: 0.034941931631645676, audioSlow: 0.11543589749484738, audioFast: 0.09077230488491152, spin: 14.205282822272496, spinVel: 0.7129558335832731, spinDir: -1),
      DynamicsSample(step: 210, time: 199.20000000000277, stateBlend: 1.9865066128671276, drive: 0.23687538410429054, audioSlow: 0.20903178238267106, audioFast: 0.22705711610998638, spin: 14.584124765651053, spinVel: 0.9237036087890452, spinDir: -1),
      DynamicsSample(step: 240, time: 199.70000000000317, stateBlend: 2, drive: 0.3705515531914049, audioSlow: 0.3519371659878911, audioFast: 0.3662118034189073, spin: 15.127339144147621, spinVel: 1.1923240365022583, spinDir: -1),
      DynamicsSample(step: 270, time: 200.20000000000357, stateBlend: 2, drive: 0.3650320601828824, audioSlow: 0.3726388029828834, audioFast: 0.37203056625922315, spin: 15.732274491004848, spinVel: 1.2098975788490036, spinDir: -1),
      DynamicsSample(step: 300, time: 200.70000000000397, stateBlend: 2.1296752741667055, drive: 0.28638326939717373, audioSlow: 0.34086042491644736, audioFast: 0.33122958867348107, spin: 16.330830548100465, spinVel: 1.1730046997553651, spinDir: -1),
      DynamicsSample(step: 330, time: 201.20000000000437, stateBlend: 2.986506612867127, drive: 0.061466978214619196, audioSlow: 0.13241645544112526, audioFast: 0.09534430231431164, spin: 16.701679392408867, spinVel: 0.4400033931042575, spinDir: -1),
      DynamicsSample(step: 360, time: 201.70000000000476, stateBlend: 3, drive: 0.7502134776651543, audioSlow: 0.7143715584524308, audioFast: 0.7990585755676841, spin: 16.594687001988195, spinVel: -1.0300034806965395, spinDir: -1),
      DynamicsSample(step: 390, time: 202.20000000000516, stateBlend: 3, drive: 0.18151236765070075, audioSlow: 0.3534417206359289, audioFast: 0.2730574331759864, spin: 16.1153029473064, spinVel: -0.6842032547561318, spinDir: -1),
      DynamicsSample(step: 420, time: 202.70000000000556, stateBlend: 3, drive: 0.19341146583118835, audioSlow: 0.21937329739194372, audioFast: 0.19435709748110575, spin: 15.919939256677353, spinVel: -0.19517056506560523, spinDir: -1),
      DynamicsSample(step: 450, time: 203.20000000000596, stateBlend: 3, drive: 0.40109778713369515, audioSlow: 0.29213786843395007, audioFast: 0.34933757749131744, spin: 15.847133023113882, spinVel: -0.30658893993722885, spinDir: -1),
      DynamicsSample(step: 480, time: 203.70000000000636, stateBlend: 3, drive: 0.22689415737627333, audioSlow: 0.6905019816418129, audioFast: 0.6419193771328248, spin: 15.287328591397557, spinVel: -1.377820280201177, spinDir: -1),
      DynamicsSample(step: 510, time: 204.20000000000675, stateBlend: 3, drive: 0.22123577929940433, audioSlow: 0.6779177129254359, audioFast: 0.6331746312215347, spin: 14.5330755831851, spinVel: -1.5702989816072483, spinDir: -1),
      DynamicsSample(step: 540, time: 204.70000000000715, stateBlend: 2.610974177499883, drive: 0.6696161997128817, audioSlow: 0.91350091309748, audioFast: 0.9500462313720663, spin: 13.750112529613265, spinVel: -1.7279223742247098, spinDir: -1),
      DynamicsSample(step: 570, time: 205.20000000000755, stateBlend: 0.04048016139861773, drive: 0.1700332578421526, audioSlow: 0.42036633721485717, audioFast: 0.3089013511025448, spin: 13.13802434345304, spinVel: -0.9881402593060398, spinDir: -1),
      DynamicsSample(step: 600, time: 205.70000000000795, stateBlend: 0, drive: 0.15171483911926567, audioSlow: 0.21508453647887235, audioFast: 0.17462918784146242, spin: 12.8134804625171, spinVel: -0.3164356172937933, spinDir: 1),
    ]),
  ]
}
