//  ConformanceTests.swift
//  OrbKitTests
//
//  Pins the Swift port to src/orb.js through the vectors generated by
//  native/conformance/generate.mjs. See native/SPEC.md §7.

import XCTest
@testable import OrbKit

final class ConformanceTests: XCTestCase {

  func testHuesMatchReference() {
    XCTAssertEqual(OrbIdentity.hues, ConformanceVectors.hues)
  }

  func testBuiltInPalettes() {
    for (i, v) in ConformanceVectors.palettes.enumerated() {
      let p = OrbIdentity.palettes[i]
      XCTAssertEqual(p.hue, v.hue)
      XCTAssertEqual(p.anchor.hex, v.anchor, "anchor for hue \(v.hue)")
      XCTAssertEqual(p.accents.map(\.hex), v.accents, "accents for hue \(v.hue)")
    }
  }

  func testCustomHues() {
    for v in ConformanceVectors.customHues {
      let p = OrbPalette(hue: v.input)
      XCTAssertEqual(p.hue!, v.hue, accuracy: 1e-9, "hue wrap for \(v.input)")
      XCTAssertEqual(p.anchor.hex, v.anchor, "anchor for hue \(v.input)")
      XCTAssertEqual(p.accents.map(\.hex), v.accents, "accents for hue \(v.input)")
    }
  }

  func testIdentityForEverySeed() {
    for v in ConformanceVectors.identity {
      let id = OrbIdentity(seed: v.seed)
      XCTAssertEqual(id.hash, v.hash, "hash of \(v.seed.debugDescription)")
      XCTAssertEqual(id.archetype.rawValue, v.archetypeIndex, "archetype of \(v.seed.debugDescription)")
      XCTAssertEqual(id.palette.hue!, v.hue, "hue of \(v.seed.debugDescription)")
      XCTAssertEqual(id.palette.anchor.hex, v.anchor)
      XCTAssertEqual(id.palette.accents.map(\.hex), v.accents)
      XCTAssertEqual(id.phase, v.phase, accuracy: 1e-9)
      XCTAssertEqual(id.spin, v.spin, accuracy: 1e-9)
      XCTAssertEqual(id.timeOffset, v.timeOffset, accuracy: 1e-9)
    }
  }

  /// Same scenario as generate.mjs: the synthetic envelope as level, a step schedule
  /// through all four states and back to idle, fixed dt.
  func testDynamicsScenario() {
    func syntheticLevel(_ t: Double) -> Double {
      let phrase = 0.55 + 0.45 * sin(0.9 * t + 2 * sin(0.37 * t))
      let syllable = 0.6 + 0.4 * sin(6.2 * t + 3 * sin(2.3 * t))
      let breath: Double = sin(0.7 * t + 1.7) > -0.6 ? 1 : 0.12
      return phrase * syllable * breath
    }
    func stateAt(_ t: Double) -> Double {
      if t < 1 { return 0 }
      if t < 3 { return 1 }
      if t < 5 { return 2 }
      if t < 9 { return 3 }
      return 0
    }

    for scenario in ConformanceVectors.dynamics {
      let id = OrbIdentity(seed: scenario.seed)
      var d = OrbDynamics()
      d.reseed(id)
      d.setState(0, instant: true)
      var time = id.timeOffset
      var expected = scenario.samples.makeIterator()
      var next = expected.next()

      for i in 0...scenario.steps {
        let t = Double(i) * scenario.dt
        d.state = stateAt(t)
        d.level = syntheticLevel(t)
        if i > 0 { time += scenario.dt }
        d.advance(to: time)

        if let s = next, s.step == i {
          let where_ = "seed \(scenario.seed.debugDescription) step \(i)"
          XCTAssertEqual(d.stateBlend, s.stateBlend, accuracy: 1e-4, "stateBlend " + where_)
          XCTAssertEqual(d.drive, s.drive, accuracy: 1e-4, "drive " + where_)
          XCTAssertEqual(d.audioSlow, s.audioSlow, accuracy: 1e-4, "audioSlow " + where_)
          XCTAssertEqual(d.audioFast, s.audioFast, accuracy: 1e-4, "audioFast " + where_)
          XCTAssertEqual(d.spin, s.spin, accuracy: 2e-3, "spin " + where_)
          XCTAssertEqual(d.spinVel, s.spinVel, accuracy: 2e-3, "spinVel " + where_)
          XCTAssertEqual(d.spinDir, s.spinDir, "spinDir " + where_)
          next = expected.next()
        }
      }
      XCTAssertNil(next, "every sample consumed")
    }
  }

  func testResolutionRules() {
    // size >= 48 uses the device scale, capped at 2x; below 48 renders at 1x.
    XCTAssertEqual(OrbResolution.pixels(size: 320, scale: 3), 640)
    XCTAssertEqual(OrbResolution.pixels(size: 320, scale: 2), 640)
    XCTAssertEqual(OrbResolution.pixels(size: 320, scale: 1), 320)
    XCTAssertEqual(OrbResolution.pixels(size: 40, scale: 3), 40)
    XCTAssertEqual(OrbResolution.pixels(size: 2000, scale: 2), 1280)
    XCTAssertEqual(OrbResolution.pixels(size: 8, scale: 1), 8)
    // Lens taper.
    XCTAssertEqual(OrbResolution.lens(.auto, size: 320, px: 640), 0.4 * OrbMath.clamp(420.0 / 640.0, 0.55, 1), accuracy: 1e-12)
    XCTAssertEqual(OrbResolution.lens(.auto, size: 40, px: 40), 0)
    XCTAssertEqual(OrbResolution.lens(.off, size: 320, px: 640), 0)
    XCTAssertEqual(OrbResolution.lens(.amplitude(0.9), size: 320, px: 640), 0.9)
  }

  func testOptionValidation() {
    var o = OrbOptions()
    o.size = 4
    XCTAssertThrowsError(try o.validate())
    o.size = 320; o.state = 3.5
    XCTAssertThrowsError(try o.validate())
    o.state = 2.5; o.lens = .amplitude(-1)
    XCTAssertThrowsError(try o.validate())
    o.lens = .auto
    XCTAssertNoThrow(try o.validate())
  }

  func testColorHexRoundTrip() {
    XCTAssertEqual(OrbColor(hex: "#e98c13")?.hex, "#e98c13")
    XCTAssertEqual(OrbColor(hex: "fff")?.hex, "#ffffff")
    XCTAssertNil(OrbColor(hex: "not a colour"))
  }
}
