// conformance.cpp — pins the C++ port to src/orb.js through the vectors generated by
// native/conformance/generate.mjs, and proves the HLSL compiles (and, when a D3D11
// device is available, renders a frame with plausible coverage). SPEC.md §7.

#include "orb/orb.h"
#include "conformance_vectors.h"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <stdexcept>
#include <string>
#include <vector>

#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <d3d11.h>
#include <d3dcompiler.h>
#include <wrl/client.h>
using Microsoft::WRL::ComPtr;
#endif

namespace {

int failures = 0;

void expect(bool ok, const std::string& what) {
  if (!ok) { failures++; std::printf("  FAIL  %s\n", what.c_str()); }
}
void expectNear(double got, double want, double tol, const std::string& what) {
  if (!(std::fabs(got - want) <= tol)) {
    failures++;
    std::printf("  FAIL  %s: got %.9g want %.9g (tol %g)\n", what.c_str(), got, want, tol);
  }
}

double syntheticLevel(double t) {
  const double phrase = 0.55 + 0.45 * std::sin(0.9 * t + 2 * std::sin(0.37 * t));
  const double syllable = 0.6 + 0.4 * std::sin(6.2 * t + 3 * std::sin(2.3 * t));
  const double breath = std::sin(0.7 * t + 1.7) > -0.6 ? 1 : 0.12;
  return phrase * syllable * breath;
}
double stateAt(double t) {
  if (t < 1) return 0;
  if (t < 3) return 1;
  if (t < 5) return 2;
  if (t < 9) return 3;
  return 0;
}

void testHues() {
  std::printf("hues\n");
  expect(orb::Identity::hues() == orb_conformance::hues, "hue table");
}

void testPalettes() {
  std::printf("built-in palettes\n");
  const auto& pals = orb::Identity::palettes();
  for (size_t i = 0; i < orb_conformance::palettes.size(); i++) {
    const auto& v = orb_conformance::palettes[i];
    expectNear(*pals[i].hue, v.hue, 0, "hue " + std::to_string(v.hue));
    expect(pals[i].anchor.hex() == v.anchor, "anchor for hue " + std::to_string(v.hue) + " got " + pals[i].anchor.hex());
    for (int k = 0; k < 3; k++) {
      expect(pals[i].accents[k].hex() == v.accents[k], "accent " + std::to_string(k) + " for hue " + std::to_string(v.hue) + " got " + pals[i].accents[k].hex());
    }
  }
  std::printf("custom hues\n");
  for (const auto& v : orb_conformance::customHues) {
    const auto p = orb::Palette::ofHue(v.input);
    expectNear(*p.hue, v.hue, 1e-9, "hue wrap for " + std::to_string(v.input));
    expect(p.anchor.hex() == v.anchor, "anchor for hue " + std::to_string(v.input));
    for (int k = 0; k < 3; k++) expect(p.accents[k].hex() == v.accents[k], "accent for hue " + std::to_string(v.input));
  }
}

void testIdentity() {
  std::printf("identity (%zu seeds)\n", orb_conformance::identity.size());
  for (const auto& v : orb_conformance::identity) {
    const orb::Identity id(v.seed);
    const std::string s = std::string("'") + v.seed + "'";
    expect(id.hash == v.hash, "hash of " + s + " got " + std::to_string(id.hash) + " want " + std::to_string(v.hash));
    expect(static_cast<int>(id.archetype) == v.archetypeIndex, "archetype of " + s);
    expectNear(*id.palette.hue, v.hue, 0, "hue of " + s);
    expect(id.palette.anchor.hex() == v.anchor, "anchor of " + s);
    for (int k = 0; k < 3; k++) expect(id.palette.accents[k].hex() == v.accents[k], "accent of " + s);
    expectNear(id.phase, v.phase, 1e-9, "phase of " + s);
    expectNear(id.spin, v.spin, 1e-9, "spin of " + s);
    expectNear(id.timeOffset, v.timeOffset, 1e-9, "timeOffset of " + s);
  }
}

void testDynamics() {
  std::printf("dynamics scenario\n");
  for (const auto& sc : orb_conformance::dynamics) {
    const orb::Identity id(sc.seed);
    orb::Dynamics d;
    d.reseed(id);
    d.setState(0, true);
    double time = id.timeOffset;
    size_t next = 0;
    for (int i = 0; i <= sc.steps; i++) {
      const double t = i * sc.dt;
      d.state = stateAt(t);
      d.level = syntheticLevel(t);
      if (i > 0) time += sc.dt;
      d.advance(time);
      if (next < sc.samples.size() && sc.samples[next].step == i) {
        const auto& s = sc.samples[next];
        const std::string where = std::string("seed '") + sc.seed + "' step " + std::to_string(i);
        expectNear(d.stateBlend, s.stateBlend, 1e-4, "stateBlend " + where);
        expectNear(d.drive, s.drive, 1e-4, "drive " + where);
        expectNear(d.audioSlow, s.audioSlow, 1e-4, "audioSlow " + where);
        expectNear(d.audioFast, s.audioFast, 1e-4, "audioFast " + where);
        expectNear(d.spin, s.spin, 2e-3, "spin " + where);
        expectNear(d.spinVel, s.spinVel, 2e-3, "spinVel " + where);
        expectNear(d.spinDir, s.spinDir, 0, "spinDir " + where);
        next++;
      }
    }
    expect(next == sc.samples.size(), "every sample consumed");
  }
}

void testResolution() {
  std::printf("resolution rules\n");
  expect(orb::pixelsFor(320, 3) == 640, "320@3x");
  expect(orb::pixelsFor(320, 2) == 640, "320@2x");
  expect(orb::pixelsFor(320, 1) == 320, "320@1x");
  expect(orb::pixelsFor(40, 3) == 40, "40@3x stays 1x");
  expect(orb::pixelsFor(2000, 2) == 1280, "cap 1280");
  expect(orb::pixelsFor(8, 1) == 8, "floor 8");
  expectNear(orb::lensFor(orb::LensChoice::auto_(), 320, 640), 0.4 * (420.0 / 640.0), 1e-12, "lens taper");
  expect(orb::lensFor(orb::LensChoice::auto_(), 40, 40) == 0, "lens off below 48");
  expect(orb::lensFor(orb::LensChoice::off(), 320, 640) == 0, "lens off");
  expect(orb::lensFor(orb::LensChoice::of(0.9), 320, 640) == 0.9, "lens explicit");
}

void testValidation() {
  std::printf("option validation\n");
  auto throws = [](orb::Options o) { try { o.validate(); return false; } catch (const std::invalid_argument&) { return true; } };
  orb::Options o; o.size = 4; expect(throws(o), "size < 8 throws");
  o = {}; o.state = 3.5; expect(throws(o), "state > 3 throws");
  o = {}; o.lens = orb::LensChoice::of(-1); expect(throws(o), "negative lens throws");
  o = {}; o.state = 2.5; expect(!throws(o), "2.5 is a legal state");
  expect(orb::Color::fromHex("#e98c13")->hex() == "#e98c13", "hex round trip");
  expect(orb::Color::fromHex("fff")->hex() == "#ffffff", "short hex");
  expect(!orb::Color::fromHex("not a colour"), "bad hex rejected");
}

void testOrbLifecycle() {
  std::printf("Orb lifecycle\n");
  orb::Options o; o.seed = "agent-42"; o.state = 1;
  orb::Orb orb(o);
  expect(orb.state() == orb::State::Listening, "mount state applies instantly");
  // 'auto' archetype is the hash-derived one, resolved on the CPU like the web does.
  expect(orb.frameSpec(1.0).arch == static_cast<double>(static_cast<int>(orb.identity().archetype)), "auto archetype resolves to the identity's");
  expect(orb.identity().archetype == orb::Archetype::Deep, "agent-42 is a deep field");
  expect(orb.dynamics().stateBlend == 1.0, "no fade-in at mount");
  orb.setState(orb::State::Speaking);
  orb.tick(0.0); orb.tick(1.0 / 60);
  expect(orb.dynamics().stateBlend > 1.0 && orb.dynamics().stateBlend < 3.0, "later changes crossfade");
  expect(orb.needsFrame(), "animating orb needs frames");
  orb.listen(orb::AudioSource::constant(0.5));
  for (int i = 0; i < 120; i++) orb.tick(0.1 + i / 60.0);
  expect(orb.dynamics().audioSlow > 0.3, "envelope follows a bound source");
  orb.unlisten();
  expect(orb.level() == 0, "unlisten decays the level input");
  auto pcm = orb::PCMSource::create();
  std::vector<float> loud(512, 0.5f);
  pcm->push(loud.data(), loud.size(), 1);
  pcm->start(); pcm->tick(1.0);
  expectNear(pcm->level(), std::min(1.0, 3.2 * 0.5), 1e-6, "PCM RMS with gain");
}

#ifdef _WIN32
void testShaderAndRender() {
  std::printf("HLSL compile\n");
  ComPtr<ID3DBlob> code, errors;
  const char* src = orb::Renderer::hlsl();
  HRESULT hr = D3DCompile(src, std::strlen(src), "orb.hlsl", nullptr, nullptr, "orb_ps", "ps_4_0",
                          D3DCOMPILE_ENABLE_STRICTNESS | D3DCOMPILE_IEEE_STRICTNESS, 0, &code, &errors);
  if (FAILED(hr)) {
    expect(false, std::string("pixel shader: ") + (errors ? static_cast<const char*>(errors->GetBufferPointer()) : "?"));
    return;
  }
  hr = D3DCompile(src, std::strlen(src), "orb.hlsl", nullptr, nullptr, "orb_vs", "vs_4_0", 0, 0, &code, &errors);
  expect(SUCCEEDED(hr), "vertex shader compiles");

  std::printf("D3D11 render (offscreen)\n");
  ComPtr<ID3D11Device> dev; ComPtr<ID3D11DeviceContext> ctx;
  const D3D_FEATURE_LEVEL lv[] = {D3D_FEATURE_LEVEL_11_0, D3D_FEATURE_LEVEL_10_0};
  hr = D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, 0, lv, 2, D3D11_SDK_VERSION, &dev, nullptr, &ctx);
  if (FAILED(hr)) hr = D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_WARP, nullptr, 0, lv, 2, D3D11_SDK_VERSION, &dev, nullptr, &ctx);
  if (FAILED(hr)) { std::printf("  skip  no D3D11 device\n"); return; }

  try {
    orb::Renderer r(dev.Get());
    const int px = 128;
    D3D11_TEXTURE2D_DESC td{};
    td.Width = td.Height = px; td.MipLevels = td.ArraySize = 1;
    td.Format = DXGI_FORMAT_B8G8R8A8_UNORM; td.SampleDesc.Count = 1;
    td.Usage = D3D11_USAGE_DEFAULT; td.BindFlags = D3D11_BIND_RENDER_TARGET;
    ComPtr<ID3D11Texture2D> tex, staging;
    dev->CreateTexture2D(&td, nullptr, &tex);
    td.Usage = D3D11_USAGE_STAGING; td.BindFlags = 0; td.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
    dev->CreateTexture2D(&td, nullptr, &staging);
    ComPtr<ID3D11RenderTargetView> rtv;
    dev->CreateRenderTargetView(tex.Get(), nullptr, &rtv);

    orb::Options o; o.seed = "agent-42"; o.size = 128; o.state = 3;
    orb::Orb orb(o);
    orb.listen(orb::AudioSource::constant(0.6));
    for (int i = 0; i < 30; i++) orb.tick(i / 60.0);
    orb::Viewport vp; vp.px = px;
    orb.draw(r, ctx.Get(), rtv.Get(), vp, 1.0, orb::Composite::Transparent);
    ctx->CopyResource(staging.Get(), tex.Get());
    D3D11_MAPPED_SUBRESOURCE map{};
    if (SUCCEEDED(ctx->Map(staging.Get(), 0, D3D11_MAP_READ, 0, &map))) {
      const auto* rows = static_cast<const uint8_t*>(map.pData);
      auto px4 = [&](int x, int y) { return rows + y * map.RowPitch + x * 4; };
      const uint8_t* centre = px4(px / 2, px / 2);
      const uint8_t* corner = px4(1, 1);
      const uint8_t* inside = px4(px / 2, px / 4);
      expect(centre[3] > 40, "centre has coverage (alpha " + std::to_string(centre[3]) + ")");
      expect(corner[3] == 0, "corner outside the disc is transparent (alpha " + std::to_string(corner[3]) + ")");
      expect(inside[3] > 0, "upper body has coverage");
      // Premultiplied: no channel may exceed alpha.
      bool premul = true;
      for (int y = 0; y < px; y += 7) for (int x = 0; x < px; x += 7) {
        const uint8_t* p = px4(x, y);
        if (p[0] > p[3] || p[1] > p[3] || p[2] > p[3]) premul = false;
      }
      expect(premul, "output is premultiplied");
      ctx->Unmap(staging.Get(), 0);
    } else {
      expect(false, "map staging");
    }
    expect(r.drawCalls() == 1, "one draw call per orb");
  } catch (const std::exception& e) {
    expect(false, std::string("renderer: ") + e.what());
  }
}
#endif

} // namespace

int main() {
  std::printf("orb conformance (C++ port vs %s)\n", "src/orb.js");
  testHues();
  testPalettes();
  testIdentity();
  testDynamics();
  testResolution();
  testValidation();
  testOrbLifecycle();
#ifdef _WIN32
  testShaderAndRender();
#endif
  if (failures) { std::printf("\n%d failure(s)\n", failures); return 1; }
  std::printf("\nall passed\n");
  return 0;
}
