// Generated by native/conformance/generate.mjs from src/orb.js@1.0.0. Do not edit.
// GLSL_GALAXY from src/orb.js, verbatim. The GLES 2.0 dialect is WebGL1's dialect.
package com.earlbalai.orb

internal const val ORB_GLSL_GALAXY: String = """
// One 1D hash behind every star position, magnitude, colour temperature, grain
// cell and meteor trajectory below.
float h1(float x) { return fract(sin(x * 127.1) * 43758.5453); }

// Agent-state basis. uState is one smoothed float in [0,3] (0 idle, 3 speaking);
// the CPU has already eased it, so what arrives here is never a step.
//
// Plateau-ramp: exactly 1 within +/-0.35 of a state, easing to 0 a unit away.
// The plateau is what stops each state reading as a permanent blend of its
// neighbours. shade() normalises the four weights, so a transition dissolves one
// look into the next rather than summing them into a brighter mush.
//
// stateBasis() in the JS is the same function, and the spin integrator uses it.
// Keep them in step.
float stateW(float s, float i) { return 1.0 - smoothstep(0.35, 1.0, abs(s - i)); }

// One meteor stream: white-hot head, fading tail. Returns (headGlow, tail, vis).
// The epoch index seeds the trajectory, so every fragment in a pass agrees on it.
//
// 'off' shifts the clock AND the epoch index, which is how thinking gets a
// second independent stream. What it must not do is shorten the period of the
// existing one: floor(t / met) jumps the moment met changes, teleporting a
// meteor mid-flight on every crossfade. Adding a stream is glitch-free,
// retuning one is not.
vec3 meteorTrail(vec2 p, float t, float met, float off) {
  float tt = t + off * met;
  float epoch = floor(tt / met) + off * 17.0;
  float ph = fract(tt / met);
  vec2 s0 = vec2(-1.1 + 2.2 * h1(epoch * 1.3), 0.85 - 1.4 * h1(epoch * 2.9));
  vec2 sd = normalize(vec2(0.7 + 0.5 * h1(epoch * 4.1), -0.35 - 0.4 * h1(epoch * 5.3)));
  vec2 head = s0 + sd * ph * 2.8;
  vec2 rel = p - head;
  float along = dot(rel, sd);
  float perp = dot(rel, vec2(-sd.y, sd.x));
  float vis = smoothstep(0.0, 0.06, ph) * smoothstep(0.5, 0.32, ph);
  float tail = exp(-perp * perp * 1600.0) * exp(along * 9.0) * step(along, 0.0)
             * smoothstep(-0.5, -0.02, along);
  float headGlow = exp(-dot(rel, rel) * 900.0);
  return vec3(headGlow, tail, vis);
}

// A whole sky as a pure function of a point on the unit sphere: tilted band of
// star dust, nebula pockets, dust lanes, three magnitude classes of twinkling
// stars, shear streaks, a pulsar.
//
// Integer rule: every frequency applied to 'lon' must be a whole number. lon is
// atan(), so it wraps at +/-pi; a fractional frequency does not tile across that
// seam and stamps a hard crease down the sphere that tumbles into view once per
// rotation. Every literal multiplying lon below is an integer on purpose.
vec4 starfield(vec3 n, float t) {
  float lon = atan(n.z, n.x);
  float lat = asin(clamp(n.y, -1.0, 1.0));

  // Three decorrelated variates off the seed phase. Band tilt, undulation,
  // width, star census, pocket hues, core direction, pulsar position and meteor
  // cadence all come off these. This is where one orb stops looking like another.
  float v1 = fract(uPhase * 7.13);
  float v2 = fract(uPhase * 3.71);
  float v3 = fract(uPhase * 5.37);

  // Archetype. uArch < 0 means derive it from the seed phase.
  //   0 spiral  a Milky-Way band
  //   1 nebula  vivid cloud over the whole sky, star-poor
  //   2 core    blazing warm bulge, star-rich
  //   3 deep    near-empty void, sparse and crystalline
  float at = uArch >= 0.0 ? uArch : floor(fract(uPhase * 9.73) * 4.0);
  float isNeb  = step(0.5, at) * (1.0 - step(1.5, at));
  float isCore = step(1.5, at) * (1.0 - step(2.5, at));
  float isDeep = step(2.5, at);

  // Density concentrates in a gaussian band around a tilted, gently undulating
  // equator. gb is signed distance from it, in radians.
  float gb = lat + (0.15 + 0.4 * v1) * sin(lon * (1.0 + floor(v2 * 2.0)) + 1.3)
           + 0.12 * sin(lon * 3.0 + t * 0.1);
  float band = exp(-gb * gb * (5.0 + 10.0 * v3));
  band = mix(band, max(band, 0.8), isNeb);   // nebula: cloud everywhere
  band *= 1.0 - 0.85 * isDeep;               // deep field: almost nothing

  // Two octaves of domain-warped wisps for the nebula, a third for the dust
  // lanes cutting across the bright band.
  float n1 = sin(lon * 2.0 + sin(lat * 3.0 + t * 0.25) * 1.6 + t * 0.15);
  float n2 = sin(lon * 5.0 - sin(lat * 4.0 - t * 0.2) * 1.2 - t * 0.22 + 2.4);
  float neb = pow(0.5 + 0.5 * n1, 2.0) * (0.45 + 0.55 * pow(0.5 + 0.5 * n2, 2.0));
  float lane = pow(0.5 + 0.5 * sin(lon * 4.0 + lat * 7.0 + sin(lon * 2.0) * 2.0), 3.0);
  float galaxy = clamp(band * neb * (1.0 - lane * (0.55 + 0.35 * v2)), 0.0, 1.0);

  // Real galactic dust is mostly cool blue-white haze. The palette rides on top
  // as a cast, re-saturated so it survives the mixing. How hard the dust leans
  // into the palette varies per orb, so a screen full of orbs reads as different
  // skies rather than one recoloured sky.
  vec3 hue = mix(mix(uC0, uC1, v1), mix(uC1, uC2, v3),
                 0.5 + 0.5 * sin(lon + lat * 2.0 - t * 0.2));
  vec3 hueGrey = vec3(dot(hue, vec3(0.299, 0.587, 0.114)));
  hue = clamp(hueGrey + (hue - hueGrey) * 1.45, 0.0, 1.0);
  vec3 dust = mix(vec3(0.72, 0.78, 0.92), hue, 0.45 + 0.3 * v1 + 0.45 * isNeb);

  // Squaring pulls the floor down so room noise does not keep the whole galaxy
  // lit, while peaks still reach full strength. aud drives brightness, audT
  // (linear, gentler) drives rates so nothing strobes.
  float aud  = uAudio * uAudio;
  float audT = uAudio;

  vec3 col = dust * galaxy * (0.6 + 0.9 * isNeb) * (1.0 + 0.85 * aud);

  // Orbital shear: faint drifting streaks inside the band. Without them the
  // galaxy only slides across the sphere instead of turning.
  float shear = sin(lon * 13.0 + lat * 4.0 - t * 0.35) * sin(lon * 5.0 + t * 0.2);
  col += dust * band * neb * max(shear, 0.0) * (0.14 + 0.26 * aud);

  // Second, fainter arm crossing the main band. Spiral depth.
  float gb2 = lat - (0.35 + 0.25 * v2) * sin(lon * 2.0 - 1.1) + 0.4;
  float arm = exp(-gb2 * gb2 * 7.0) * neb;
  col += mix(dust, uC1, 0.35) * arm * 0.2;

  // The void is never pure black: a breathing whisper of deep indigo carrying
  // the orb's hue. It covers the whole sphere, so it is the strongest identity
  // cue in the image.
  vec3 voidGlow = mix(vec3(0.04, 0.03, 0.1), mix(uC0, mix(uC1, uC2, v3), v1) * 0.22, 0.75);
  col += voidGlow * (0.5 + 0.22 * sin(t * 0.4 + lon)) * (0.4 + 0.6 * band);

  // Warm amber deep inside the densest part of the band.
  col += vec3(1.0, 0.88, 0.68) * pow(band, 4.0) * pow(neb, 2.0) * (0.4 + 0.55 * aud);

  // core archetype: bulge pinned to the rotating sphere (n, not the view
  // normal), so it wheels around the limb as the galaxy turns.
  float ca = v2 * 6.28318;
  vec3 Cdir = normalize(vec3(cos(ca) * 0.85, 0.6 * (v3 - 0.5), sin(ca) * 0.85));
  float bulge = max(dot(n, Cdir), 0.0);
  col += mix(vec3(1.0, 0.85, 0.6), uC2, 0.25)
       * (pow(bulge, 14.0) * 1.6 + pow(bulge, 4.0) * 0.5) * isCore;

  // Two layers of nebula pocket in different hues, slowly breathing.
  float pocket = pow(neb, 5.0) * band * (0.7 + 0.3 * sin(t * (0.6 + 1.6 * audT) + lon * 3.0));
  col += mix(uC2, uC0, fract(v1 + 0.5 * sin(lon * 2.0) + 0.5))
       * pocket * (0.5 + 0.4 * v2 + 0.8 * isNeb) * (1.0 + 1.1 * aud);
  float pocket2 = pow(0.5 + 0.5 * sin(lon * 3.0 + lat * 4.0 - t * 0.18 + 2.0), 6.0) * band;
  col += mix(uC1, uC2, v3) * pocket2 * (0.25 + 0.3 * v1 + 0.5 * isNeb) * (1.0 + 0.9 * aud);

  // Detail budget by rendered size, not CSS size. Below ~90 device px the fine
  // grain and the faint star class stop reading as texture and start strobing
  // as the sphere tumbles, so they fade out.
  float detail = smoothstep(90.0, 200.0, uRes.y);

  // Sub-pixel star dust packed into the band. Long exposure rather than
  // gradient.
  vec2 gg = vec2(lon, lat) * 34.0;
  vec2 gc = floor(gg);
  vec2 gf = fract(gg);
  float gh = h1(gc.x * 3.7 + gc.y * 11.3);
  vec2 gp = vec2(0.2 + 0.6 * h1(gh * 91.0), 0.2 + 0.6 * h1(gh * 47.0));
  // cos(lat) stretch keeps grains and stars round where the lat/lon
  // parameterisation converges at the poles.
  float gd = length((gf - gp) * vec2(cos(lat), 1.0));
  // Sharper than this and each grain lands on ~1px of a ~3px cell, which reads
  // as pixel noise rather than dust. Wider gaussian, fewer lit cells, same
  // long-exposure texture without the speckle.
  float grain = exp(-gd * gd * 240.0 * clamp(uRes.y / 420.0, 0.22, 1.0))
              * step(0.58, gh) * (0.15 + 0.85 * band);
  col += vec3(0.88, 0.9, 1.0) * grain * 0.32 * detail;

  // w is this layer's alpha: how much of the glass the sky replaces.
  float w = clamp(galaxy * 0.7 + pow(band, 4.0) * 0.25, 0.0, 1.0);

  // Three magnitude classes on three lattice scales: a few bright, many mid,
  // dense faint dust. Constant bound, index never assigned, so it stays inside
  // GLSL ES 1.00 Appendix A.
  for (int s = 0; s < 3; s++) {
    float K = s == 0 ? 6.0 : (s == 1 ? 11.0 : 19.0);
    vec2 g = vec2(lon, lat) * K;
    vec2 cell = floor(g);
    vec2 f = fract(g);
    float hx = h1(cell.x * 13.7 + cell.y * 7.3 + float(s) * 91.0);
    float hy = h1(cell.x * 5.1 + cell.y * 17.9 + float(s) * 37.0);
    vec2 sp = vec2(0.15 + 0.7 * hx, 0.15 + 0.7 * hy);
    float d = length((f - sp) * vec2(cos(lat), 1.0));

    // Star census by archetype: nebulae star-poor, cores star-rich, deep fields
    // sparse.
    float census = (v2 - 0.5) * 0.2 + 0.35 * isNeb - 0.2 * isCore + 0.3 * isDeep;
    // Audio lowers the visibility threshold, so fainter stars fade in as the
    // voice rises and the sky deepens while the agent speaks.
    float keep = step((s == 2 ? 0.3 : 0.55) + census - 0.16 * aud,
                      h1(hx * 89.0 + hy * 31.0) + band * 0.25);

    // At small sizes a star has to stay ~1px wide and twinkle gently or it
    // aliases into strobing as the sphere tumbles.
    float resFac = clamp(uRes.y / 420.0, 0.22, 1.0);
    // Audio drives rate and depth of scintillation together. Clamped at zero so
    // the faintest stars wink right out at high depth; without that it reads as
    // a brightness ramp, not twinkle.
    float twRate  = (1.5 + 3.0 * hx) * (1.0 + 2.4 * audT);
    float twDepth = 0.4 + 0.42 * aud;
    float tw = mix(0.92, max(0.0, (1.0 - twDepth) + twDepth * sin(t * twRate + hx * 40.0)), resFac);

    // Radius from the hash, squared, so there are few big ones and many small.
    // Brightness follows size, roughly a real magnitude distribution.
    float hz = h1(hx * 53.0 + hy * 71.0 + cell.x);
    float sizeJit = 0.35 + 1.8 * hz * hz;
    float sharp = (s == 0 ? 260.0 : (s == 1 ? 700.0 : 1600.0)) / (sizeJit * (1.0 + 0.35 * aud)) * resFac;
    float star = exp(-d * d * sharp) * keep * tw;

    // Near-white with a faint colour-temperature spread.
    vec3 tint = mix(vec3(1.0),
                    hx < 0.33 ? vec3(0.85, 0.9, 1.0)
                              : (hx < 0.66 ? vec3(1.0, 0.95, 0.85) : mix(vec3(1.0), uC1, 0.3)),
                    0.6);
    float bright = (s == 0 ? 1.7 : (s == 1 ? 0.9 : 0.5)) * (0.55 + 0.7 * sizeJit) * (1.0 + 0.85 * aud);
    float starFade = mix(s == 2 ? 0.14 : 0.45, 1.0, detail);
    col += tint * star * bright * starFade;

    // Brightest class gets a halo and a diffraction cross.
    if (s == 0) {
      float big = smoothstep(1.2, 2.0, sizeJit);
      col += tint * exp(-d * d * 60.0) * (0.18 + 0.34 * aud) * big * tw * starFade;
      vec2 dd = (f - sp) * vec2(cos(lat), 1.0);
      float spike = exp(-dd.x * dd.x * 1200.0) * exp(-dd.y * dd.y * 26.0)
                  + exp(-dd.y * dd.y * 1200.0) * exp(-dd.x * dd.x * 26.0);
      col += tint * spike * (0.3 + 0.6 * aud) * big * tw * starFade;
      w = max(w, spike * 0.3 * big * starFade);
    }
    w = max(w, star * min(bright, 1.5) * starFade);
  }

  // One flashing star per orb, with a halo. pow(pd, 900) is tight enough to be
  // a point; audio pushes the beat brighter and faster.
  float pa = v1 * 6.28318;
  vec3 P = normalize(vec3(sin(pa) * 0.9, 1.4 * (v2 - 0.5), cos(pa) * 0.9));
  float pd = max(dot(n, P), 0.0);
  float beat = pow(0.5 + 0.5 * sin(t * (1.2 + v3 + 1.5 * uAudio) + v3 * 6.28), 8.0);
  beat = min(1.0, beat + 0.6 * uAudio);
  float pulsarFade = mix(0.45, 1.0, detail);
  col += vec3(0.9, 0.95, 1.0)
       * (pow(pd, 900.0) * (0.6 + 1.2 * beat) + pow(pd, 110.0) * 0.5 * beat) * pulsarFade;
  w = max(w, pow(pd, 900.0) * (0.5 + 0.5 * beat) * pulsarFade);

  return vec4(min(col, vec3(1.0)), min(w, 1.0));
}

// Sample the tumbling sphere. Three composed rotations: a roll about the view
// axis, a tilt about x whose angle precesses, and the CPU-integrated spin about
// y. One rotation only slides the pattern sideways; three give a marble turned
// in the hand, so the galaxy travels over the poles and never repeats a pass.
vec4 sphereAt(vec3 n, float spin, float t) {
  float roll = t * 0.13;
  float cr = cos(roll), sr = sin(roll);
  n = vec3(cr * n.x - sr * n.y, sr * n.x + cr * n.y, n.z);

  float tilt = 0.45 + 0.35 * sin(t * 0.24);
  float cx = cos(tilt), sx = sin(tilt);
  n = vec3(n.x, cx * n.y - sx * n.z, sx * n.y + cx * n.z);

  float cs = cos(spin), ss = sin(spin);
  n = vec3(cs * n.x + ss * n.z, n.y, -ss * n.x + cs * n.z);

  return starfield(n, t);
}

// The whole orb as a pure function of the pre-lens screen point p. Purity is
// required: the chromatic lens in main() calls this three times per fragment at
// three displaced coordinates and keeps one channel from each.
vec4 shade(vec2 p) {
  float r = length(p);
#ifndef DUAL_LAYER
  // No lens in the batch program, so nothing ever samples a tile's corners.
  // Discarding them skips the galaxy for ~21% of the fragments.
  if (r > 1.0) { discard; }
#endif
  float t = uTime * 0.8 + uPhase;

  // Four normalised weights off one smoothed scalar. Everything per-state below
  // is a lerp against these, so a change dissolves rather than cuts, and the sum
  // stays 1 so no state can brighten the orb just by existing.
  float wIdle   = stateW(uState, 0.0);
  float wListen = stateW(uState, 1.0);
  float wThink  = stateW(uState, 2.0);
  float wSpeak  = stateW(uState, 3.0);
  float wSum = max(wIdle + wListen + wThink + wSpeak, 0.0001);
  wIdle /= wSum; wListen /= wSum; wThink /= wSum; wSpeak /= wSum;

  // Clamping rr just under 1 closes three NaN paths at once: sqrt(1 - rr*rr)
  // never takes a negative radicand, refract()'s internal k = 1 - 0.5625*rr^2
  // stays >= 0.4376 so it cannot hit total internal reflection and return
  // vec3(0.0), and normalize(N + R*dHit) therefore never sees the zero vector.
  //
  // Past r = 1 the colours smear outward. That overscan is deliberate: the lens
  // needs real pixels to displace, or it pulls transparent samples and stamps a
  // hard arc inside the silhouette. The circular cut happens in CSS.
  float rr = min(r, 0.9995);
  float z = sqrt(1.0 - rr * rr);
  vec3 N = vec3(p.x, p.y, z);
  float fres = pow(1.0 - z, 2.4);          // 0 at the centre -> 1 at the limb

  // Dual-layer glass. Refract at the near wall, follow the ray through the body,
  // sample the galaxy again where it exits the far wall.
  //
  // For a unit sphere the chord from surface point N along unit direction R has
  // length -2*dot(N, R): |N + dR|^2 = 1 with |N| = 1 gives d^2 + 2d*dot(N,R) = 0.
  // So the exit point is N + R*dHit and normalize() only mops up float error.
  // No marching, no iteration.
  vec3 I = vec3(0.0, 0.0, -1.0);
  vec3 R = refract(I, N, 0.75);
  float dHit = -2.0 * dot(N, R);
  vec3 B = normalize(N + R * dHit);

  // Pattern time gets a non-linear warp from two incommensurate sines so the
  // drift never settles into a visible loop. Spin angle is separate, integrated
  // on the CPU (uSpin), so it can accelerate, ease and reverse.
  float sv = fract(uPhase * 6.31);
  float sw = fract(uPhase * 2.17);
  float tWarp = t
    + (0.9 + 1.3 * sv) * sin(t * (0.09 + 0.07 * sw))
    + (0.5 + 0.8 * sw) * sin(t * (0.21 + 0.09 * sv) + 2.6);

  // Both layers ride the same rotating sphere, so the far wall counter-slides in
  // true perspective as the ball turns and it reads as one object.
  vec4 front = sphereAt(N, uSpin, tWarp);
#ifdef DUAL_LAYER
  vec4 back = sphereAt(B, uSpin, tWarp * 0.8 + 2.7);
#else
  vec4 back = vec4(0.0);
#endif

  // Near-black void carrying the anchor colour, brighter at the rim. uBg leaks
  // through at a few percent, which is what keeps the orb reading as translucent
  // glass instead of a flat disc, and why 'background' has to track the page
  // rather than be hard-coded.
  vec3 voidCol = mix(uAnchor * 0.05, uAnchor * 0.40, fres);
  // A little of the page's light scatters through the body. The page itself is
  // not painted here: we emit real coverage below and let the compositor put the
  // actual backdrop behind us, so this works over a card, a gradient or a photo
  // and not only over the one colour we guessed.
  vec3 col = mix(voidCol, voidCol + uBg * 0.18, 1.0 - fres);

  // mix, not add: the band replaces the glass colour where it lives, so it still
  // reads on a light page instead of clipping to white.
  float fa = clamp(front.a, 0.0, 1.0);
  float ba = clamp(back.a, 0.0, 1.0);
  col = mix(col, back.rgb, ba * 0.16);     // far-wall echo, deliberately faint
  col = mix(col, front.rgb, fa * 0.85);

  // listening: cool cast on the body only, before aurora, meteors and speculars
  // go in, so the orb cools without the highlights going dead. Desaturating
  // toward grey and re-tinting keeps the luminance, so it is the same brightness
  // as idle, just colder.
  float coolLum = dot(col, vec3(0.299, 0.587, 0.114));
  col = mix(col, vec3(coolLum) * vec3(0.74, 0.88, 1.22), wListen * 0.5);

  // Coverage handed to the compositor. Glass haze thickens toward the limb
  // (fresnel) and the galaxy occludes what it covers.
  float bodyA = 0.34 + 0.46 * fres;
  float alpha = clamp(bodyA + fa * 0.72 + ba * 0.10, 0.0, 1.0);

  // Aurora, drawn in view space rather than sphere space so the curtains always
  // hang in the visible upper sky while the galaxy tumbles behind them. Green at
  // the base climbing into violet, pulled toward the orb's palette by a per-orb
  // amount.
  float alon = atan(N.x, N.z);
  float speech = pow(0.5 + 0.5 * sin(alon * 3.0 + sin(alon * 7.0 + t * 1.1) * 0.7 + t * 0.5), 3.0)
               * (0.55 + 0.45 * sin(alon * 5.0 - t * 0.65 + 1.7));
  float sky = -N.y;                        // the quad's v is flipped: -N.y is up
  float hang = smoothstep(-0.15, 0.5, sky);
  float rays = 0.7 + 0.3 * sin(alon * 24.0 + sin(alon * 9.0 - t * 0.8) * 2.0 + t * 1.6);
  float aur = clamp(speech, 0.0, 1.0) * hang * rays * (1.0 + 2.2 * uAudio);
  float av = fract(uPhase * 2.93);
  vec3 aurCol = mix(vec3(0.12, 0.95, 0.55), vec3(0.45, 0.35, 1.0),
                    smoothstep(0.0, 0.95, sky + 0.35 * speech));
  aurCol = mix(aurCol, mix(uC0, uC2, av), 0.15 + 0.4 * av);
  // Loudest state cue in the image. Thinking stays low deliberately, so the core
  // is what reads as busy.
  float aurGain = wIdle * 0.42 + wListen * 0.72 + wThink * 0.50 + wSpeak * 1.30;
  col += aurCol * aur * 0.8 * aurGain;

  // A meteor every few seconds on a fresh trajectory. Thinking adds a second
  // stream on a shorter offset clock, which quickens the sky without the primary
  // stream ever jumping (see meteorTrail). wThink is constant across an orb, so
  // the branch costs nothing in divergence and skips the work in the other three
  // states.
  float met = 4.5 + 3.5 * fract(uPhase * 4.91);
  vec3 m0 = meteorTrail(p, t, met, 0.0);
  col += (vec3(1.0) * m0.x * 1.2 + mix(vec3(1.0), uC1, 0.3) * m0.y * 0.85) * m0.z;
  if (wThink > 0.01) {
    vec3 m1 = meteorTrail(p, t, met * 0.61, 0.37);
    col += (vec3(1.0) * m1.x * 1.1 + mix(vec3(1.0), uC1, 0.3) * m1.y * 0.8) * m1.z * wThink;
  }

  // thinking: no external audio in this state, so the activity has to be
  // intrinsic. A deep inner pulse breathing at ~0.5 Hz, phase-offset per orb,
  // and a bead of light orbiting the core, which is the part the eye tracks.
  // Spin roughly triples on the CPU side at the same time (advanceDynamics).
  float thinkPulse = 0.42 + 0.58 * pow(0.5 + 0.5 * sin(t * 3.1 + uPhase * 4.0), 2.0);
  col += mix(uC1, vec3(1.0), 0.35) * pow(1.0 - rr, 3.0) * wThink * thinkPulse * 1.15;
  float beadA = t * 1.35 + uPhase * 3.0;
  vec2 bead = vec2(cos(beadA), sin(beadA)) * 0.42;
  vec2 bd = p - bead;
  col += mix(uC2, vec3(1.0), 0.30) * exp(-dot(bd, bd) * 55.0) * wThink * 0.5;

  // A broad diffuse terminator sweeping around the sphere, brightening whole
  // regions of sky and dust in turn. Makes the ball feel lit rather than printed.
  vec3 LD = normalize(vec3(0.85 * sin(t * 0.42), 0.45 * sin(t * 0.26 + 1.2), 0.5));
  float diffuse = 0.62 + 0.65 * max(dot(N, LD), 0.0);
  diffuse *= 1.0 + 0.35 * uAudio;          // the whole sky breathes with the voice
  col *= diffuse;

  // Voice light. Speaking pushes the inner flare, listening pushes the rim
  // instead: same level, different reading. The agent lights from within when it
  // talks and catches the room's light at its edge when it is taking the room in.
  vec3 voiceCol = mix(uC1, vec3(1.0, 0.97, 0.9), 0.45);
  col += voiceCol * pow(1.0 - rr, 1.8) * uAudio * (0.5 + 0.35 * wSpeak);  // inner flare
  col += (uC1 * 0.7 + vec3(0.12)) * fres * uAudio * (0.65 + 0.55 * wListen);  // rim catch

  // Concentric shockwaves while the voice is live. Keyed off the radius so the
  // ring spacing scales with the orb, and multiplied by col so it only lights
  // what is already bright.
  col += col * uAudio * 0.18 * sin(t * 14.0 + rr * 40.0 + uPhase * 7.0);

  // Faint atmospheric scatter opposite the moving key light.
  float counter = max(dot(N.xy, -LD.xy), 0.0) * fres;
  col += mix(uC0, vec3(0.5, 0.6, 0.9), 0.5) * counter * 0.18;

  // Speculars off the sphere normal. The key light drifts and breathes in
  // intensity. A highlight that sits still reads as CG immediately.
  vec3 L1 = normalize(vec3(-0.45 + 0.3 * sin(t * 0.34),
                            0.62 + 0.2 * sin(t * 0.27 + 1.7), 0.64));
  float keyAmp = 0.5 * (0.78 + 0.22 * sin(t * 0.45 + 2.2));
  col += vec3(1.0) * pow(max(dot(N, L1), 0.0), 150.0) * keyAmp;

  vec3 LS = normalize(vec3(sin(t * 0.07) * 0.9, 0.35 + 0.3 * cos(t * 0.05), 0.7));
  col += vec3(1.0) * pow(max(dot(N, LS), 0.0), 7.0) * 0.05;        // broad soft sheen

  vec3 L2 = normalize(vec3(0.52, -0.5 + 0.12 * sin(t * 0.09), 0.69));
  col += vec3(1.0) * pow(max(dot(N, L2), 0.0), 140.0) * 0.25;      // counter glint

  // A bubble's edge catches a touch of the band's colour.
  col = mix(col, front.rgb, fa * fres * 0.3);

  // Whisper of limb darkening.
  float limb = smoothstep(0.94, 1.0, rr);
  col = mix(col, col * 0.85, limb * 0.4);

  // idle: last word, over everything including the speculars, so the orb goes
  // uniformly quieter rather than selectively dull. Landing before the luminance
  // term below also makes it slightly more transparent, which suits waiting.
  col *= 1.0 - wIdle * 0.16;

  // Everything added after the body is emitted light and has to survive on any
  // backdrop, so luminance drives coverage: bright things go opaque, the dark
  // glass body stays translucent and the page shows through.
  float lum = dot(col, vec3(0.299, 0.587, 0.114));
  alpha = clamp(alpha + lum * 0.85, 0.0, 1.0);

  return vec4(col, alpha);
}"""
